-- Migration 0003: Update users table for system user support (PRD V2 Section 2.4.3)
-- Note: is_unlimited column already exists in users table from 0001_initial.sql
-- This migration is kept for historical purposes but does nothing
