/**
 * Tests for ID generation utilities
 */
import { describe, it, expect } from "vitest";
import { generateId, extractTimestamp, isValidId } from "@/utils/id-generator";

describe("id-generator", () => {
  describe("generateId", () => {
    it("should generate a valid UUID v4", () => {
      const id = generateId();

      expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);
    });

    it("should generate unique IDs", () => {
      const id1 = generateId();
      const id2 = generateId();

      expect(id1).not.toBe(id2);
    });

    it("should generate IDs with correct format", () => {
      const id = generateId();
      const parts = id.split("-");

      expect(parts).toHaveLength(5);
      expect(parts[0]).toHaveLength(8);
      expect(parts[1]).toHaveLength(4);
      expect(parts[2]).toHaveLength(4);
      expect(parts[3]).toHaveLength(4);
      expect(parts[4]).toHaveLength(12);
    });

    it("should be a valid ID according to isValidId", () => {
      const id = generateId();
      expect(isValidId(id)).toBe(true);
    });
  });

  describe("extractTimestamp", () => {
    it("should return null for UUID v4 (random)", () => {
      const id = "550e8400-e29b-41d4-a716-446655440000";
      const timestamp = extractTimestamp(id);

      expect(timestamp).toBeNull();
    });

    it("should return null for invalid UUID format", () => {
      const timestamp = extractTimestamp("not-a-uuid");
      expect(timestamp).toBeNull();
    });

    it("should return null for empty string", () => {
      const timestamp = extractTimestamp("");
      expect(timestamp).toBeNull();
    });

    it("should return null for UUID v4 generated by generateId", () => {
      const id = generateId();
      const timestamp = extractTimestamp(id);

      expect(timestamp).toBeNull();
    });

    it("should extract timestamp from UUID v7", () => {
      // UUID v7: 017f22e2-79b0-7cc3-98c4-dc0c0c07398f
      // First 48 bits: 017f22e279b0 (hex) = 1698765432000 (approx)
      const id = "017f22e2-79b0-7cc3-98c4-dc0c0c07398f";
      const timestamp = extractTimestamp(id);

      expect(timestamp).toBeGreaterThan(0);
      expect(timestamp).toBeLessThan(Date.now() + 31536000000); // Less than ~1 year from now
    });

    it("should handle UUID v7 with different versions", () => {
      // Valid UUID v7 format
      const id = "018fffff-ffff-7fff-ffff-ffffffffffff";
      const timestamp = extractTimestamp(id);

      expect(timestamp).not.toBeNull();
      expect(timestamp).toBeGreaterThan(0);
    });
  });

  describe("isValidId", () => {
    it("should return true for valid UUID v4", () => {
      expect(isValidId("550e8400-e29b-41d4-a716-446655440000")).toBe(true);
    });

    it("should return true for valid UUID v7", () => {
      expect(isValidId("017f22e2-79b0-7cc3-98c4-dc0c0c07398f")).toBe(true);
    });

    it("should return false for invalid format", () => {
      expect(isValidId("not-a-uuid")).toBe(false);
      expect(isValidId("550e8400-e29b-41d4-a716")).toBe(false);
      expect(isValidId("")).toBe(false);
    });

    it("should return true for generated IDs", () => {
      const id = generateId();
      expect(isValidId(id)).toBe(true);
    });
  });
});
